config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "cart_sessions"}
  resources :carts
  resources :cart_items
  resources :charges
  resources :purchases
  resources :user_items
  resources :items
  resources :ratings
  resources :users, only: [:index, :show]
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :user_items
	has_many :users, through: :user_items
	has_many :ratings, dependent: :destroy
	has_many :carts
	has_many :carts, through: :cart_items
	has_one_attached :image, dependent: :destroy

	def avg_rating
    ratings.average(:stars)
  end

	def favorited?(current_user)
		@user_item = UserItem.find_by(item_id: self.id, user_id: current_user.id)
		if @user_item.nil?
			return false
		end
		return @user_item.favorited
	end
	
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user_items
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
       petergate(roles: [:root_admin], multiple: true)                                      ##
  ############################################################################################ 
 
  has_many :given_ratings, class_name: 'Rating', foreign_key: 'user_id', dependent: :destroy
  has_many :user_items, dependent: :destroy
  has_many :items, through: :user_items
  has_many :ratings, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :first_name, presence: true 
  validates :last_name, presence: true

  def full_name
    return first_name + " " + last_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @total = @cart.items.sum(:price)
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = current_user.carts.new(cart_params)
    if @cart.save
      respond_to do |format|
        format.html {redirect_to @carts}
        format.js
      end
    end  
  end

  def show
    @cart = Cart.find(params[:id])
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update_attributes(cart_params)
    render_to @carts
  end

  def destroy
    @cart = Cart.find(params[:id])
    if @cart.destroy
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  private
  def cart_params
    params.require(:cart).permit(:completed)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to current_user
  	else
  		redirect_to items_path
  	end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, root_admin: :all
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    respond_to do |format|
      if @item.destroy
        format.html {redirect_to users_path}
        format.js
      end
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :description, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_helper
	  if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path) +
      "<br>".html_safe +
      (link_to "Login", new_user_session_path)
    else
      link_to "Logout", destroy_user_session_path, method: :delete
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1 class="wish">Cart</h1>
<div class="container">
	<div class="row">
		<div id="cart-items">
			<% @cart.cart_items.each do |cart_item| %>
  			<div class="list-group" id="cart_item<%= cart_item.item.id %>">
  				<div class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
              <h4 class="mb-1"><%= cart_item.item.name %> $<%= cart_item.item.price %></h4>  
            </div>
            <p class="mb-1"><%= cart_item.item.description %>
              <%= link_to "Remove Item", cart_item_path(cart_item), method: :delete, remote: true, class: "remove-cart-item", data: {type: 'json'} %>
            </p>
          </div>
  			</div>
			<% end %>
		</div>
    <%= form_with url: charges_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <div class="list-group-item"><span><h4 class="total-amount"><u>Amount:</u> $<%= @total %></h4></span></div>
        </label>
      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="A month's subscription"
              data-amount="<%= @total*100 %>"
              data-locale="auto"></script>
    <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<h1>Carts#show</h1>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>

app/views/items/_item.html.erb
<div class="carousel-cell" id="items-list">
	<div class="card" id="card">
		<div class="item" id="item-<%= item.id %>" data-info="<%= {description: item.description, name: item.name, price: item.price, rating: item.avg_rating}.to_json %>">
			<div class="card-header bg-transparent border-primary">
				<%= item.name %>
				<% if user_signed_in? %>
					<%= form_with model: UserItem.new, class: "form-useritem", remote: true do |f|%>
						<% if item.favorited?(current_user) %>
							<%= f.submit "", type: :image, src: asset_path("heart.svg"), class: "favorite-button" %>
						<% else %>
							<%= f.submit "", type: :image, src: asset_path("heart-outline.svg"), class: "favorite-button" %>
						<% end %>
						<%= f.hidden_field :item_id, value: item.id %>
						<%= f.hidden_field :favorited, value: !item.favorited?(current_user), class: 'hidden-favorited' %>
					<% end %>
				<% end %>
			</div>
			<div class="card-body text-primary">
				<h5 class="card-title">$<%= item.price %>
				<% if logged_in?(:root_admin) %>
				  <%= link_to(edit_item_path(item)) do %>
		      	<i class="material-icons">edit</i>
					<% end %>
					<%= link_to(item, method: :delete, remote: true) do %>
		      	<i class="material-icons">delete</i>
					<% end %>
				<% else %>
					<% if user_signed_in? %>
						<% if @cart.items.include?(item) %>
          		<div class="shoppingcart" data-id="<%= item.id %>">
          			<i class="material-icons">shopping_cart</i>
          		</div>
	          <% else %>	
	          	<div class="shoppingcart" data-id="<%= item.id %>">
	          		<i class="material-icons">add_shopping_cart</i>
	          	</div>
						<% end %>
					<% end %>
				<% end %>
				<button class="btn btn-primary navbar-btn sidebarCollapse" type="button" data-toggle="collapse" data-target="#card-info<%= item.id %>" aria-expanded="false" aria-controls="card-info<%= item.id %>"><span class="glyphicon glyphicon-align-left"></span>More</button>
				</h5>
				 <% if item.image.attached? %>
					 <%= image_tag item.image, class: "rounded img-thumbnail" %>
				 <% end %>
				<div class="row">
					<div class="col">
						<% if !logged_in?(:root_admin) %>
							<div class="card-body">
								<p class="card text">
									<%= form_with model: Rating.new, id: "form-for-ratings" do |f| %>
										<div class="ratings-boxes" id="item-<%= item.id %>">
											<div class="rating-label"><%= f.label :rate %></div>
											<div class="rating-box"><%= f.select(:stars, [1, 2, 3, 4, 5], {}, class: "square-rating") %></div>
										</div>
										<%= hidden_field_tag :item_id, item.id %>
										<%= f.submit class: "btn btn-primary" %>
									<% end %>
							  </p>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/create.js.erb
<% if @cart.items.include?(item) %>
	$('.shoppingcart').on('click', function(){
		$('.material-icons').text('shopping_cart');
	});
<% else %>
	$('.shoppingcart').on('click', function(){
		$('.material-icons').text('add_shopping_cart');
	});
<% end %>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h2>Admin <%= current_user.first_name %></h2>

<div class="form-group">
	<%= form_with model: @item, data: {"parsely-validate": ''}, local: true do |f| %>
		<%= f.text_field :name, placeholder: 'Name', class: "form-control" %>
		<%= f.number_field :price, placeholder: 'Price', class: "form-control" %>
		<div class="custom-file">
			<%= f.file_field :image, class: "custom-file-input" %>
			<%= f.label :image, 'Upload Image', class: 'custom-file-label' %>
		</div>
		<%= f.text_field :description, placeholder: 'Description', class: "form-control" %>
		<%= f.submit class: "btn btn-primary" %>
	<% end %>	
</div>

app/views/items/index.html.erb
<nav id="sidebar" class="inactive">
	<span id="close-sidebar">X</span>
	<div class="sidebar-header">
		<h2><u>Blue Lily Candles</u></h2>
	</div>
	<ul class="list-group">
		<li class="list-group-item">
			<p>
				<div class="name"><u>Name:</u> <span></span></div>
				<div class="description"><u>Description:</u> <span></span></div>
				<div class="rating"><u>Rating:</u> <span></span>/5</div>
				<div class="price"><u>Price:</u> $<span></span></div>
			</p>
		</li>
	</ul>	
</nav>
<div class="carousel">
	<%= render @items %>	
</div>							

app/views/items/new.html.erb
<h1>Add Item</h1>
<div class="form-group">
	<%= form_with model: @item, data: {"parsely-validate": ''}, local: true do |f| %>
		<%= f.text_field :name, placeholder: 'Name', required: true, class: "form-control" %>
		<%= f.number_field :price, placeholder: 'Price', required: true, class: "form-control" %>
		<div class="custom-file">
			<%= f.file_field :image, class: "custom-file-input" %>
			<%= f.label :image, 'Upload Image', class: 'custom-file-label' %>
		</div>
		<%= f.text_field :description, placeholder: 'Description', required: true, class: "form-control" %>
		<%= f.submit class: "btn btn-primary" %>
	<% end %>	
</div>

app/views/items/show.html.erb
<h1>Items#show</h1>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
	

app/views/users/show.html.erb
<h1>Users Cart</h1>
<h1><%= current_user.first_name %> <%= current_user.last_name %></h1>	