config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "cart_sessions"}
  resources :carts
  resources :cart_items
  resources :charges
  resources :purchases
  resources :user_items
  resources :items
  resources :ratings
  resources :users, only: [:index, :show]
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :user_items
	has_many :users, through: :user_items
	has_many :ratings, dependent: :destroy
	has_many :carts
	has_many :carts, through: :cart_items
	has_one_attached :image, dependent: :destroy

	def avg_rating
    ratings.average(:stars)
  end

	def favorited?(current_user)
		@user_item = UserItem.find_by(item_id: self.id, user_id: current_user.id)
		if @user_item.nil?
			return false
		end
		return @user_item.favorited
	end
	
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user_items
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
       petergate(roles: [:root_admin], multiple: true)                                      ##
  ############################################################################################ 
 
  has_many :given_ratings, class_name: 'Rating', foreign_key: 'user_id', dependent: :destroy
  has_many :user_items, dependent: :destroy
  has_many :items, through: :user_items
  has_many :ratings, dependent: :destroy
  has_many :carts, dependent: :destroy

  validates :first_name, presence: true 
  validates :last_name, presence: true

  def full_name
    return first_name + " " + last_name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		redirect_to current_user
  	else
  		redirect_to items_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def login_helper
	  if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path) +
      "<br>".html_safe +
      (link_to "Login", new_user_session_path)
    else
      link_to "Logout", destroy_user_session_path, method: :delete
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_items_helper.rb
module UserItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlueLily</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p> 
    <% end %>
    <% if params[:controller] == "items" && params[:action] == "index" %>
      <div class="m-header">
        <h1 class="main-header">
          <span>b</span>
          <span>l</span>
          <span>u</span>
          <span>e</span>
          <span>l</span>
          <span>i</span>
          <span>l</span>
          <span>l</span>
          <span>y</span>
          <span></span>
          <span>c</span>
          <span>a</span>
          <span>n</span>
          <span>d</span>
          <span>l</span>
          <span>e</span>
          <span>s</span>
        </h1>
      </div>
     <div class="img" id="cover-image">
       <%= image_tag src="cover.jpg", class: "img-fluid" %>
     </div>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to items_path, class: "nav-item nav-link" do %>
        <i class="material-icons">home</i>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
            <%= link_to "Favorites", user_items_path, class: "nav-item nav-link" %>
            <% if !logged_in?(:root_admin) %>
              <div class="cart-wrapper">
                <div class="count"><%= @cart.items.count %></div>
                <%= link_to carts_path, class: 'nav-item nav-link' do %>
                  <i class="material-icons">shopping_cart</i>
                <% end %>
              </div>
            <% end %>
            <% if logged_in?(:root_admin) %>
              <%= link_to "Add Item(s)", new_item_path , class: "nav-item nav-link" %>
            <% end %>
          <% else %>
            <%= link_to "Sign-up", new_user_registration_path, class: "nav-item nav-link" %>
            <%= link_to "Login", new_user_session_path, class: "nav-item nav-link"  %>
          <% end %> 
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>